export const labelStrings = {
  "ar": {
    "copy2clipboard": "نسخ إلى الحافظة",
    "post2x": "نشر على X",
    "post2threds": "نشر على Threads",
    "post2bluesky": "نشر على Bluesky",
    "post2mastodon": "نشر على Mastodon Social",
    "post2linkedin": "نشر على LinkedIn",
    "post2telegram": "نشر على Telegram",
    "post2line": "نشر على LINE",
    "refreshPageInfo": "إعادة تحميل الصفحة",
    "onError": "لاستخدام هذا الامتداد، يجب تفعيله قبل تحميل الصفحة. بعد تحديث الصفحة في Safari، حاول مرة أخرى.",
    "editActions": "تحرير الإجراءات...",
    "editDone": "تم"
  },
  "ar-SA": {
    "copy2clipboard": "نسخ إلى الحافظة",
    "post2x": "نشر على X",
    "post2threds": "نشر على Threads",
    "post2bluesky": "نشر على Bluesky",
    "post2mastodon": "نشر على Mastodon Social",
    "post2linkedin": "نشر على LinkedIn",
    "post2telegram": "نشر على Telegram",
    "post2line": "نشر على LINE",
    "refreshPageInfo": "إعادة تحميل الصفحة",
    "onError": "لاستخدام هذا الامتداد، يجب تفعيله قبل تحميل الصفحة. بعد تحديث الصفحة في Safari، حاول مرة أخرى.",
    "editActions": "تحرير الإجراءات...",
    "editDone": "تم"
  },
  "de": {
    "copy2clipboard": "In die Zwischenablage kopieren",
    "post2x": "Auf X posten",
    "post2threds": "Auf Threads posten",
    "post2bluesky": "Auf Bluesky posten",
    "post2mastodon": "Auf Mastodon Social posten",
    "post2linkedin": "Auf LinkedIn posten",
    "post2telegram": "Auf Telegram posten",
    "post2line": "Auf LINE posten",
    "refreshPageInfo": "Seite neu laden",
    "onError": "Um diese Erweiterung zu verwenden, muss sie vor dem Laden der Seite aktiviert werden. Bitte versuchen Sie es erneut, nachdem Sie die Seite in Safari aktualisiert haben.",
    "editActions": "Aktionen bearbeiten...",
    "editDone": "Fertig"
  },
  "en": {
    "copy2clipboard": "Copy to Clipboard",
    "post2x": "Post to X",
    "post2threds": "Post to Threads",
    "post2bluesky": "Post to Bluesky",
    "post2mastodon": "Post to Mastodon Social",
    "post2linkedin": "Post to LinkedIn",
    "post2telegram": "Post to Telegram",
    "post2line": "Post to LINE",
    "refreshPageInfo": "Reload Page",
    "onError": "To use this extension, it must be enabled before loading the page. Please try again after refreshing the page in Safari.",
    "editActions": "Edit Actions...",
    "editDone": "Done"
  },
  "es": {
    "copy2clipboard": "Copiar al portapapeles",
    "post2x": "Publicar en X",
    "post2threds": "Publicar en Threads",
    "post2bluesky": "Publicar en Bluesky",
    "post2mastodon": "Publicar en Mastodon Social",
    "post2linkedin": "Publicar en LinkedIn",
    "post2telegram": "Publicar en Telegram",
    "post2line": "Publicar en LINE",
    "refreshPageInfo": "Recargar página",
    "onError": "Para usar esta extensión, debe estar habilitada antes de cargar la página. Intenta de nuevo después de actualizar la página en Safari.",
    "editActions": "Editar acciones...",
    "editDone": "Hecho"
  },
  "es-MX": {
    "copy2clipboard": "Copiar al portapapeles",
    "post2x": "Publicar en X",
    "post2threds": "Publicar en Threads",
    "post2bluesky": "Publicar en Bluesky",
    "post2mastodon": "Publicar en Mastodon Social",
    "post2linkedin": "Publicar en LinkedIn",
    "post2telegram": "Publicar en Telegram",
    "post2line": "Publicar en LINE",
    "refreshPageInfo": "Recargar página",
    "onError": "Para usar esta extensión, debe estar habilitada antes de cargar la página. Intenta de nuevo después de actualizar la página en Safari.",
    "editActions": "Editar acciones...",
    "editDone": "Hecho"
  },
  "fr": {
    "copy2clipboard": "Copier dans le presse-papiers",
    "post2x": "Publier sur X",
    "post2threds": "Publier sur Threads",
    "post2bluesky": "Publier sur Bluesky",
    "post2mastodon": "Publier sur Mastodon Social",
    "post2linkedin": "Publier sur LinkedIn",
    "post2telegram": "Publier sur Telegram",
    "post2line": "Publier sur LINE",
    "refreshPageInfo": "Recharger la page",
    "onError": "Pour utiliser cette extension, elle doit être activée avant de charger la page. Veuillez réessayer après avoir actualisé la page dans Safari.",
    "editActions": "Modifier les actions...",
    "editDone": "Terminé"
  },
  "hi": {
    "copy2clipboard": "क्लिपबोर्ड में कॉपी करें",
    "post2x": "X पर पोस्ट करें",
    "post2threds": "Threads पर पोस्ट करें",
    "post2bluesky": "Bluesky पर पोस्ट करें",
    "post2mastodon": "Mastodon Social पर पोस्ट करें",
    "post2linkedin": "LinkedIn पर पोस्ट करें",
    "post2telegram": "Telegram पर पोस्ट करें",
    "post2line": "LINE पर पोस्ट करें",
    "refreshPageInfo": "पृष्ठ को पुनः लोड करें",
    "onError": "इस एक्सटेंशन का उपयोग करने के लिए, इसे पेज लोड करने से पहले सक्षम करना होगा। सफारी में पेज को रीफ्रेश करने के बाद फिर से प्रयास करें।",
    "editActions": "क्रियाएँ संपादित करें...",
    "editDone": "पूर्ण"
  },
  "id": {
    "copy2clipboard": "Salin ke Papan Klip",
    "post2x": "Posting ke X",
    "post2threds": "Posting ke Threads",
    "post2bluesky": "Posting ke Bluesky",
    "post2mastodon": "Posting ke Mastodon Social",
    "post2linkedin": "Posting ke LinkedIn",
    "post2telegram": "Posting ke Telegram",
    "post2line": "Posting ke LINE",
    "refreshPageInfo": "Muat Ulang Halaman",
    "onError": "Untuk menggunakan ekstensi ini, ekstensi harus diaktifkan sebelum memuat halaman. Silakan coba lagi setelah menyegarkan halaman di Safari.",
    "editActions": "Edit Tindakan...",
    "editDone": "Selesai"
  },
  "ja": {
    "copy2clipboard": "クリップボードにコピー",
    "post2x": "Xに投稿",
    "post2threds": "Threadsに投稿",
    "post2bluesky": "Blueskyに投稿",
    "post2mastodon": "Mastodon Socialに投稿",
    "post2linkedin": "LinkedInに投稿",
    "post2telegram": "Telegramに投稿",
    "post2line": "LINEに投稿",
    "refreshPageInfo": "ページを再読み込み",
    "onError": "この機能拡張を使用するには、ページを読み込む前に有効化する必要があります。Safariでページを更新してから、再度お試しください。",
    "editActions": "アクションを編集...",
    "editDone": "完了"
  },
  "ko-KR": {
    "copy2clipboard": "클립보드에 복사",
    "post2x": "X에 게시",
    "post2threds": "Threads에 게시",
    "post2bluesky": "Bluesky에 게시",
    "post2mastodon": "Mastodon Social에 게시",
    "post2linkedin": "LinkedIn에 게시",
    "post2telegram": "Telegram에 게시",
    "post2line": "LINE에 게시",
    "refreshPageInfo": "페이지 새로 고침",
    "onError": "이 확장 프로그램을 사용하려면 페이지를 로드하기 전에 활성화되어 있어야 합니다. Safari에서 페이지를 새로 고친 후 다시 시도하세요.",
    "editActions": "작업 편집...",
    "editDone": "완료"
  },
  "nl": {
    "copy2clipboard": "Kopiëren naar klembord",
    "post2x": "Posten op X",
    "post2threds": "Posten op Threads",
    "post2bluesky": "Posten op Bluesky",
    "post2mastodon": "Posten op Mastodon Social",
    "post2linkedin": "Posten op LinkedIn",
    "post2telegram": "Posten op Telegram",
    "post2line": "Posten op LINE",
    "refreshPageInfo": "Pagina herladen",
    "onError": "Om deze extensie te gebruiken, moet deze vóór het laden van de pagina worden ingeschakeld. Probeer het opnieuw nadat u de pagina in Safari hebt vernieuwd.",
    "editActions": "Acties bewerken...",
    "editDone": "Klaar"
  },
  "pt": {
    "copy2clipboard": "Copiar para a área de transferência",
    "post2x": "Postar no X",
    "post2threds": "Postar no Threads",
    "post2bluesky": "Postar no Bluesky",
    "post2mastodon": "Postar no Mastodon Social",
    "post2linkedin": "Postar no LinkedIn",
    "post2telegram": "Postar no Telegram",
    "post2line": "Postar no LINE",
    "refreshPageInfo": "Recarregar página",
    "onError": "Para usar esta extensão, ela deve estar ativada antes de carregar a página. Tente novamente após atualizar a página no Safari.",
    "editActions": "Editar ações...",
    "editDone": "Concluído"
  },
  "pt-PT": {
    "copy2clipboard": "Copiar para a área de transferência",
    "post2x": "Publicar no X",
    "post2threds": "Publicar no Threads",
    "post2bluesky": "Publicar no Bluesky",
    "post2mastodon": "Publicar no Mastodon Social",
    "post2linkedin": "Publicar no LinkedIn",
    "post2telegram": "Publicar no Telegram",
    "post2line": "Publicar no LINE",
    "refreshPageInfo": "Recarregar página",
    "onError": "Para usar esta extensão, ela deve estar ativada antes de carregar a página. Tente novamente após atualizar a página no Safari.",
    "editActions": "Editar ações...",
    "editDone": "Concluído"
  },
  "pt-BR": {
    "copy2clipboard": "Copiar para a área de transferência",
    "post2x": "Publicar no X",
    "post2threds": "Publicar no Threads",
    "post2bluesky": "Publicar no Bluesky",
    "post2mastodon": "Publicar no Mastodon Social",
    "post2linkedin": "Publicar no LinkedIn",
    "post2telegram": "Publicar no Telegram",
    "post2line": "Publicar no LINE",
    "refreshPageInfo": "Recarregar página",
    "onError": "Para usar esta extensão, ela deve estar ativada antes de carregar a página. Tente novamente após atualizar a página no Safari.",
    "editActions": "Editar ações...",
    "editDone": "Concluído"
  },
  "th": {
    "copy2clipboard": "คัดลอกไปยังคลิปบอร์ด",
    "post2x": "โพสต์ไปที่ X",
    "post2threds": "โพสต์ไปที่ Threads",
    "post2bluesky": "โพสต์ไปที่ Bluesky",
    "post2mastodon": "โพสต์ไปที่ Mastodon Social",
    "post2linkedin": "โพสต์ไปที่ LinkedIn",
    "post2telegram": "โพสต์ไปที่ Telegram",
    "post2line": "โพสต์ไปที่ LINE",
    "refreshPageInfo": "รีโหลดหน้าเว็บ",
    "onError": "ในการใช้ส่วนขยายนี้ จำเป็นต้องเปิดใช้งานก่อนโหลดหน้าเว็บ กรุณากดปุ่มด้านล่างเพื่อทดลองอีกครั้งหลังจากที่อัปเดตหน้าใน Safari",
    "editActions": "แก้ไขการกระทำ...",
    "editDone": "เสร็จสิ้น"
  },
  "tr": {
    "copy2clipboard": "Panoya Kopyala",
    "post2x": "X'e Gönder",
    "post2threds": "Threads'e Gönder",
    "post2bluesky": "Bluesky'e Gönder",
    "post2mastodon": "Mastodon Social'e Gönder",
    "post2linkedin": "LinkedIn'e Gönder",
    "post2telegram": "Telegram'a Gönder",
    "post2line": "LINE'a Gönder",
    "refreshPageInfo": "Sayfayı Yenile",
    "onError": "Bu uzantıyı kullanmak için, sayfayı yüklemeden önce etkinleştirilmiş olmalıdır. Safari'de sayfayı yeniledikten sonra tekrar deneyin.",
    "editActions": "Eylemleri Düzenle...",
    "editDone": "Tamamlandı"
  },
  "zh": {
    "copy2clipboard": "复制到剪贴板",
    "post2x": "发布到X",
    "post2threds": "发布到Threads",
    "post2bluesky": "发布到BlueSky",
    "post2mastodon": "发布到Mastodon Social",
    "post2linkedin": "发布到LinkedIn",
    "post2telegram": "发布到Telegram",
    "post2line": "发布到LINE",
    "refreshPageInfo": "重新加载页面",
    "onError": "要使用此扩展程序，必须在加载页面之前启用。请在Safari中刷新页面后重试。",
    "editActions": "编辑操作...",
    "editDone": "完成"
  },
  "zh-CN": {
    "copy2clipboard": "复制到剪贴板",
    "post2x": "发布到X",
    "post2threds": "发布到Threads",
    "post2bluesky": "发布到BlueSky",
    "post2mastodon": "发布到Mastodon Social",
    "post2linkedin": "发布到LinkedIn",
    "post2telegram": "发布到Telegram",
    "post2line": "发布到LINE",
    "refreshPageInfo": "重新加载页面",
    "onError": "要使用此扩展程序，必须在加载页面之前启用。请在Safari中刷新页面后重试。",
    "editActions": "编辑操作...",
    "editDone": "完成"
  },
  "zh-TW": {
    "copy2clipboard": "複製到剪貼簿",
    "post2x": "發佈到X",
    "post2threds": "發佈到Threads",
    "post2bluesky": "發佈到BlueSky",
    "post2mastodon": "發佈到Mastodon Social",
    "post2linkedin": "發佈到LinkedIn",
    "post2telegram": "發佈到Telegram",
    "post2line": "發佈到LINE",
    "refreshPageInfo": "重新載入頁面",
    "onError": "要使用此擴充功能，必須在載入頁面之前啟用。請在Safari中重新載入頁面後再試一次。",
    "editActions": "編輯操作...",
    "editDone": "完成"
  },
  "zh-HK": {
    "copy2clipboard": "複製到剪貼簿",
    "post2x": "發佈到X",
    "post2threds": "發佈到Threads",
    "post2bluesky": "發佈到BlueSky",
    "post2mastodon": "發佈到Mastodon Social",
    "post2linkedin": "發佈到LinkedIn",
    "post2telegram": "發佈到Telegram",
    "post2line": "發佈到LINE",
    "refreshPageInfo": "重新載入頁面",
    "onError": "要使用此擴充功能，必須在載入頁面之前啟用。請在Safari中重新載入頁面後再試一次。",
    "editActions": "編輯操作...",
    "editDone": "完成"
  },
  "it": {
    "copy2clipboard": "Copia negli Appunti",
    "post2x": "Pubblica su X",
    "post2threds": "Pubblica su Threads",
    "post2bluesky": "Pubblica su Bluesky",
    "post2mastodon": "Pubblica su Mastodon Social",
    "post2linkedin": "Pubblica su LinkedIn",
    "post2telegram": "Pubblica su Telegram",
    "post2line": "Pubblica su LINE",
    "refreshPageInfo": "Ricarica Pagina",
    "onError": "Per utilizzare questa estensione, deve essere abilitata prima di caricare la pagina. Per favore, riprova dopo aver aggiornato la pagina in Safari.",
    "editActions": "Modifica Azioni...",
    "editDone": "Fatto"
  },
  "uk": {
    "copy2clipboard": "Скопіювати в буфер обміну",
    "post2x": "Опублікувати в X",
    "post2threds": "Опублікувати в Threads",
    "post2bluesky": "Опублікувати в Bluesky",
    "post2mastodon": "Опублікувати в Mastodon Social",
    "post2linkedin": "Опублікувати в LinkedIn",
    "post2telegram": "Опублікувати в Telegram",
    "post2line": "Опублікувати в LINE",
    "refreshPageInfo": "Перезавантажити сторінку",
    "onError": "Щоб використовувати це розширення, воно повинно бути увімкнене перед завантаженням сторінки. Спробуйте знову після оновлення сторінки в Safari.",
    "editActions": "Редагувати дії...",
    "editDone": "Готово"
  },
  "ca": {
    "copy2clipboard": "Copiar al portapapers",
    "post2x": "Publicar a X",
    "post2threds": "Publicar a Threads",
    "post2bluesky": "Publicar a Bluesky",
    "post2mastodon": "Publicar a Mastodon Social",
    "post2linkedin": "Publicar a LinkedIn",
    "post2telegram": "Publicar a Telegram",
    "post2line": "Publicar a LINE",
    "refreshPageInfo": "Tornar a carregar la pàgina",
    "onError": "Per utilitzar aquesta extensió, ha d'estar activada abans de carregar la pàgina. Torneu-ho a intentar després d'actualitzar la pàgina a Safari.",
    "editActions": "Editar accions...",
    "editDone": "Fet"
  },
  "el": {
    "copy2clipboard": "Αντιγραφή στο πρόχειρο",
    "post2x": "Δημοσίευση στο X",
    "post2threds": "Δημοσίευση στα Threads",
    "post2bluesky": "Δημοσίευση στο Bluesky",
    "post2mastodon": "Δημοσίευση στο Mastodon Social",
    "post2linkedin": "Δημοσίευση στο LinkedIn",
    "post2telegram": "Δημοσίευση στο Telegram",
    "post2line": "Δημοσίευση στο LINE",
    "refreshPageInfo": "Επαναφόρτωση σελίδας",
    "onError": "Για να χρησιμοποιήσετε αυτήν την επέκταση, πρέπει να είναι ενεργοποιημένη πριν από την φόρτωση της σελίδας. Δοκιμάστε ξανά μετά την ανανέωση της σελίδας στο Safari.",
    "editActions": "Επεξεργασία ενεργειών...",
    "editDone": "Έγινε"
  },
  "hr": {
    "copy2clipboard": "Kopiraj u međuspremnik",
    "post2x": "Objavi na X",
    "post2threds": "Objavi na Threads",
    "post2bluesky": "Objavi na Bluesky",
    "post2mastodon": "Objavi na Mastodon Social",
    "post2linkedin": "Objavi na LinkedIn",
    "post2telegram": "Objavi na Telegram",
    "post2line": "Objavi na LINE",
    "refreshPageInfo": "Ponovno učitaj stranicu",
    "onError": "Da biste koristili ovu ekstenziju, mora biti omogućena prije učitavanja stranice. Pokušajte ponovo nakon što osvježite stranicu u Safariju.",
    "editActions": "Uredi radnje...",
    "editDone": "Gotovo"
  },
  "sv": {
    "copy2clipboard": "Kopiera till urklipp",
    "post2x": "Publicera på X",
    "post2threds": "Publicera på Threads",
    "post2bluesky": "Publicera på Bluesky",
    "post2mastodon": "Publicera på Mastodon Social",
    "post2linkedin": "Publicera på LinkedIn",
    "post2telegram": "Publicera på Telegram",
    "post2line": "Publicera på LINE",
    "refreshPageInfo": "Ladda om sidan",
    "onError": "För att använda denna tillägg måste den vara aktiverad innan sidan laddas. Försök igen efter att du har uppdaterat sidan i Safari.",
    "editActions": "Redigera åtgärder...",
    "editDone": "Klar"
  },
  "sk": {
    "copy2clipboard": "Kopírovať do schránky",
    "post2x": "Zverejniť na X",
    "post2threds": "Zverejniť na Threads",
    "post2bluesky": "Zverejniť na Bluesky",
    "post2mastodon": "Zverejniť na Mastodon Social",
    "post2linkedin": "Zverejniť na LinkedIn",
    "post2telegram": "Zverejniť na Telegram",
    "post2line": "Zverejniť na LINE",
    "refreshPageInfo": "Obnoviť stránku",
    "onError": "Na používanie tohto rozšírenia musí byť aktivované pred načítaním stránky. Skúste to znova po obnovení stránky v Safari.",
    "editActions": "Upraviť akcie...",
    "editDone": "Hotovo"
  },
  "cs": {
    "copy2clipboard": "Kopírovat do schránky",
    "post2x": "Odeslat na X",
    "post2threds": "Odeslat na Threads",
    "post2bluesky": "Odeslat na Bluesky",
    "post2mastodon": "Odeslat na Mastodon Social",
    "post2linkedin": "Odeslat na LinkedIn",
    "post2telegram": "Odeslat na Telegram",
    "post2line": "Odeslat na LINE",
    "refreshPageInfo": "Obnovit stránku",
    "onError": "Pro použití tohoto rozšíření musí být aktivováno před načtením stránky. Zkuste to znovu po obnovení stránky v Safari.",
    "editActions": "Upravit akce...",
    "editDone": "Hotovo"
  },
  "da": {
    "copy2clipboard": "Kopier til udklipsholder",
    "post2x": "Post til X",
    "post2threds": "Post til Threads",
    "post2bluesky": "Post til Bluesky",
    "post2mastodon": "Post til Mastodon Social",
    "post2linkedin": "Post til LinkedIn",
    "post2telegram": "Post til Telegram",
    "post2line": "Post til LINE",
    "refreshPageInfo": "Opdater side",
    "onError": "For at bruge denne udvidelse skal den være aktiveret, før siden indlæses. Prøv igen efter at have opdateret siden i Safari.",
    "editActions": "Rediger handlinger...",
    "editDone": "Færdig"
  },
  "nb": {
    "copy2clipboard": "Kopier til utklippstavle",
    "post2x": "Legg ut til X",
    "post2threds": "Legg ut til Threads",
    "post2bluesky": "Legg ut til Bluesky",
    "post2mastodon": "Legg ut til Mastodon Social",
    "post2linkedin": "Legg ut til LinkedIn",
    "post2telegram": "Legg ut til Telegram",
    "post2line": "Legg ut til LINE",
    "refreshPageInfo": "Last inn siden på nytt",
    "onError": "For å bruke denne utvidelsen må den være aktivert før siden lastes. Prøv igjen etter å ha oppdatert siden i Safari.",
    "editActions": "Rediger handlinger...",
    "editDone": "Ferdig"
  },
  "hu": {
    "copy2clipboard": "Másolás a vágólapra",
    "post2x": "Közzététel az X-en",
    "post2threds": "Közzététel a Threads-en",
    "post2bluesky": "Közzététel a Bluesky-n",
    "post2mastodon": "Közzététel a Mastodon Social-on",
    "post2linkedin": "Közzététel a LinkedIn-en",
    "post2telegram": "Közzététel a Telegram-on",
    "post2line": "Közzététel a LINE-on",
    "refreshPageInfo": "Az oldal újratöltése",
    "onError": "Ahhoz, hogy ezt az alkalmazást használni tudja, engedélyezni kell az oldal betöltése előtt. Kérjük, próbálja újra az oldal Safari-ban történő frissítése után.",
    "editActions": "Akciók szerkesztése...",
    "editDone": "Kész"
  },
  "fi": {
    "copy2clipboard": "Kopioi leikepöydälle",
    "post2x": "Julkaise X:ssä",
    "post2threds": "Julkaise Threadsissä",
    "post2bluesky": "Julkaise Blueskyssä",
    "post2mastodon": "Julkaise Mastodon Socialissa",
    "post2linkedin": "Julkaise LinkedIn:ssä",
    "post2telegram": "Julkaise Telegramissa",
    "post2line": "Julkaise LINE:ssä",
    "refreshPageInfo": "Lataa sivu uudelleen",
    "onError": "Jotta voit käyttää tätä laajennusta, se on otettava käyttöön ennen sivun lataamista. Yritä uudelleen, kun olet päivittänyt sivun Safarissa.",
    "editActions": "Muokkaa toimintoja...",
    "editDone": "Valmis"
  },
  "fr-CA": {
    "copy2clipboard": "Copier dans le presse-papiers",
    "post2x": "Publier sur X",
    "post2threds": "Publier sur Threads",
    "post2bluesky": "Publier sur Bluesky",
    "post2mastodon": "Publier sur Mastodon Social",
    "post2linkedin": "Publier sur LinkedIn",
    "post2telegram": "Publier sur Telegram",
    "post2line": "Publier sur LINE",
    "refreshPageInfo": "Recharger la page",
    "onError": "Pour utiliser cette extension, elle doit être activée avant de charger la page. Veuillez réessayer après avoir actualisé la page dans Safari.",
    "editActions": "Modifier les actions...",
    "editDone": "Terminé"
  },
  "vi": {
    "copy2clipboard": "Sao chép vào Clipboard",
    "post2x": "Đăng lên X",
    "post2threds": "Đăng lên Threads",
    "post2bluesky": "Đăng lên Bluesky",
    "post2mastodon": "Đăng lên Mastodon Social",
    "post2linkedin": "Đăng lên LinkedIn",
    "post2telegram": "Đăng lên Telegram",
    "post2line": "Đăng lên LINE",
    "refreshPageInfo": "Tải lại trang",
    "onError": "Để sử dụng tiện ích mở rộng này, bạn phải kích hoạt nó trước khi tải trang. Vui lòng thử lại sau khi làm mới trang trong Safari.",
    "editActions": "Chỉnh sửa hành động...",
    "editDone": "Xong"
  },
  "he": {
    "copy2clipboard": "העתק ללוח",
    "post2x": "פרסם ל-X",
    "post2threds": "פרסם ל-Threads",
    "post2bluesky": "פרסם ל-Bluesky",
    "post2mastodon": "פרסם ל-Mastodon Social",
    "post2linkedin": "פרסם ל-LinkedIn",
    "post2telegram": "פרסם ל-Telegram",
    "post2line": "פרסם ל-LINE",
    "refreshPageInfo": "רענן דף",
    "onError": "כדי להשתמש בתוסף זה, יש להפעיל אותו לפני טעינת הדף. אנא נסה שוב לאחר רענון הדף ב-Safari.",
    "editActions": "ערוך פעולות...",
    "editDone": "סיים"
  },
  "pl": {
    "copy2clipboard": "Skopiuj do schowka",
    "post2x": "Opublikuj na X",
    "post2threds": "Opublikuj na Threads",
    "post2bluesky": "Opublikuj na Bluesky",
    "post2mastodon": "Opublikuj na Mastodon Social",
    "post2linkedin": "Opublikuj na LinkedIn",
    "post2telegram": "Opublikuj na Telegram",
    "post2line": "Opublikuj na LINE",
    "refreshPageInfo": "Odśwież stronę",
    "onError": "Aby użyć tego rozszerzenia, musi być ono włączone przed załadowaniem strony. Spróbuj ponownie po odświeżeniu strony w Safari.",
    "editActions": "Edytuj akcje...",
    "editDone": "Gotowe"
  },
  "ms": {
    "copy2clipboard": "Salin ke Papan Klip",
    "post2x": "Kongsi di X",
    "post2threds": "Kongsi di Threads",
    "post2bluesky": "Kongsi di Bluesky",
    "post2mastodon": "Kongsi di Mastodon Social",
    "post2linkedin": "Kongsi di LinkedIn",
    "post2telegram": "Kongsi di Telegram",
    "post2line": "Kongsi di LINE",
    "refreshPageInfo": "Muat Semula Halaman",
    "onError": "Untuk menggunakan sambungan ini, ia mesti diaktifkan sebelum memuatkan halaman. Sila cuba lagi selepas menyegarkan halaman di Safari.",
    "editActions": "Edit Tindakan...",
    "editDone": "Selesai"
  },
  "ro": {
    "copy2clipboard": "Copiază în Clipboard",
    "post2x": "Publică pe X",
    "post2threds": "Publică pe Threads",
    "post2bluesky": "Publică pe Bluesky",
    "post2mastodon": "Publică pe Mastodon Social",
    "post2linkedin": "Publică pe LinkedIn",
    "post2telegram": "Publică pe Telegram",
    "post2line": "Publică pe LINE",
    "refreshPageInfo": "Reîncarcă pagina",
    "onError": "Pentru a folosi această extensie, trebuie să fie activată înainte de a încărca pagina. Te rugăm să încerci din nou după ce ai reîncărcat pagina în Safari.",
    "editActions": "Editează acțiunile...",
    "editDone": "Finalizat"
  },
  "ru": {
    "copy2clipboard": "Скопировать в буфер обмена",
    "post2x": "Опубликовать в X",
    "post2threds": "Опубликовать в Threads",
    "post2bluesky": "Опубликовать в Bluesky",
    "post2mastodon": "Опубликовать в Mastodon Social",
    "post2linkedin": "Опубликовать в LinkedIn",
    "post2telegram": "Опубликовать в Telegram",
    "post2line": "Опубликовать в LINE",
    "refreshPageInfo": "Перезагрузить страницу",
    "onError": "Для использования этого расширения его нужно активировать перед загрузкой страницы. Пожалуйста, попробуйте снова после перезагрузки страницы в Safari.",
    "editActions": "Редактировать действия...",
    "editDone": "Готово"
  },
  "en-GB": {
    "copy2clipboard": "Copy to Clipboard",
    "post2x": "Post to X",
    "post2threds": "Post to Threads",
    "post2bluesky": "Post to Bluesky",
    "post2mastodon": "Post to Mastodon Social",
    "post2linkedin": "Post to LinkedIn",
    "post2telegram": "Post to Telegram",
    "post2line": "Post to LINE",
    "refreshPageInfo": "Reload Page",
    "onError": "To use this extension, it must be enabled before loading the page. Please try again after refreshing the page in Safari.",
    "editActions": "Edit Actions...",
    "editDone": "Done"
  },
  "en-AU": {
    "copy2clipboard": "Copy to Clipboard",
    "post2x": "Post to X",
    "post2threds": "Post to Threads",
    "post2bluesky": "Post to Bluesky",
    "post2mastodon": "Post to Mastodon Social",
    "post2linkedin": "Post to LinkedIn",
    "post2telegram": "Post to Telegram",
    "post2line": "Post to LINE",
    "refreshPageInfo": "Reload Page",
    "onError": "To use this extension, it must be enabled before loading the page. Please try again after refreshing the page in Safari.",
    "editActions": "Edit Actions...",
    "editDone": "Done"
  },
};

export const getCurrentLangCode = () => {
  const langCode = window.navigator.language || 'en';

  return labelStrings[langCode]
    ? langCode
    : (labelStrings[langCode.substring(0, 2)] ? langCode.substring(0, 2) : 'en');
};
