export const labelStrings = {
  "ar": {
    "copy2clipboard": "نسخ إلى الحافظة",
    "post2x": "نشر على X",
    "post2threds": "نشر على Threads",
    "post2bluesky": "نشر على Bluesky",
    "post2mastodon": "نشر على Mastodon Social",
    "post2linkedin": "نشر على LinkedIn",
    "post2telegram": "نشر على Telegram",
    "post2line": "نشر على LINE",
    "refreshPageInfo": "إعادة تحميل الصفحة",
    "onError": "لاستخدام هذا الامتداد، يجب تفعيله قبل تحميل الصفحة. بعد تحديث الصفحة في Safari، حاول مرة أخرى.",
    "editActions": "تحرير الإجراءات...",
    "editDone": "تم"
  },
  "ar-SA": {
    "copy2clipboard": "نسخ إلى الحافظة",
    "post2x": "نشر على X",
    "post2threds": "نشر على Threads",
    "post2bluesky": "نشر على Bluesky",
    "post2mastodon": "نشر على Mastodon Social",
    "post2linkedin": "نشر على LinkedIn",
    "post2telegram": "نشر على Telegram",
    "post2line": "نشر على LINE",
    "refreshPageInfo": "إعادة تحميل الصفحة",
    "onError": "لاستخدام هذا الامتداد، يجب تفعيله قبل تحميل الصفحة. بعد تحديث الصفحة في Safari، حاول مرة أخرى.",
    "editActions": "تحرير الإجراءات...",
    "editDone": "تم"
  },
  "de": {
    "copy2clipboard": "In die Zwischenablage kopieren",
    "post2x": "Auf X posten",
    "post2threds": "Auf Threads posten",
    "post2bluesky": "Auf Bluesky posten",
    "post2mastodon": "Auf Mastodon Social posten",
    "post2linkedin": "Auf LinkedIn posten",
    "post2telegram": "Auf Telegram posten",
    "post2line": "Auf LINE posten",
    "refreshPageInfo": "Seite neu laden",
    "onError": "Um diese Erweiterung zu verwenden, muss sie vor dem Laden der Seite aktiviert werden. Bitte versuchen Sie es erneut, nachdem Sie die Seite in Safari aktualisiert haben.",
    "editActions": "Aktionen bearbeiten...",
    "editDone": "Fertig"
  },
  "en": {
    "copy2clipboard": "Copy to Clipboard",
    "post2x": "Post to X",
    "post2threds": "Post to Threads",
    "post2bluesky": "Post to Bluesky",
    "post2mastodon": "Post to Mastodon Social",
    "post2linkedin": "Post to LinkedIn",
    "post2telegram": "Post to Telegram",
    "post2line": "Post to LINE",
    "refreshPageInfo": "Reload Page",
    "onError": "To use this extension, it must be enabled before loading the page. Please try again after refreshing the page in Safari.",
    "editActions": "Edit Actions...",
    "editDone": "Done"
  },
  "es": {
    "copy2clipboard": "Copiar al portapapeles",
    "post2x": "Publicar en X",
    "post2threds": "Publicar en Threads",
    "post2bluesky": "Publicar en Bluesky",
    "post2mastodon": "Publicar en Mastodon Social",
    "post2linkedin": "Publicar en LinkedIn",
    "post2telegram": "Publicar en Telegram",
    "post2line": "Publicar en LINE",
    "refreshPageInfo": "Recargar página",
    "onError": "Para usar esta extensión, debe estar habilitada antes de cargar la página. Intenta de nuevo después de actualizar la página en Safari.",
    "editActions": "Editar acciones...",
    "editDone": "Hecho"
  },
  "es-MX": {
    "copy2clipboard": "Copiar al portapapeles",
    "post2x": "Publicar en X",
    "post2threds": "Publicar en Threads",
    "post2bluesky": "Publicar en Bluesky",
    "post2mastodon": "Publicar en Mastodon Social",
    "post2linkedin": "Publicar en LinkedIn",
    "post2telegram": "Publicar en Telegram",
    "post2line": "Publicar en LINE",
    "refreshPageInfo": "Recargar página",
    "onError": "Para usar esta extensión, debe estar habilitada antes de cargar la página. Intenta de nuevo después de actualizar la página en Safari.",
    "editActions": "Editar acciones...",
    "editDone": "Hecho"
  },
  "fr": {
    "copy2clipboard": "Copier dans le presse-papiers",
    "post2x": "Publier sur X",
    "post2threds": "Publier sur Threads",
    "post2bluesky": "Publier sur Bluesky",
    "post2mastodon": "Publier sur Mastodon Social",
    "post2linkedin": "Publier sur LinkedIn",
    "post2telegram": "Publier sur Telegram",
    "post2line": "Publier sur LINE",
    "refreshPageInfo": "Recharger la page",
    "onError": "Pour utiliser cette extension, elle doit être activée avant de charger la page. Veuillez réessayer après avoir actualisé la page dans Safari.",
    "editActions": "Modifier les actions...",
    "editDone": "Terminé"
  },
  "hi": {
    "copy2clipboard": "क्लिपबोर्ड में कॉपी करें",
    "post2x": "X पर पोस्ट करें",
    "post2threds": "Threads पर पोस्ट करें",
    "post2bluesky": "Bluesky पर पोस्ट करें",
    "post2mastodon": "Mastodon Social पर पोस्ट करें",
    "post2linkedin": "LinkedIn पर पोस्ट करें",
    "post2telegram": "Telegram पर पोस्ट करें",
    "post2line": "LINE पर पोस्ट करें",
    "refreshPageInfo": "पृष्ठ को पुनः लोड करें",
    "onError": "इस एक्सटेंशन का उपयोग करने के लिए, इसे पेज लोड करने से पहले सक्षम करना होगा। सफारी में पेज को रीफ्रेश करने के बाद फिर से प्रयास करें।",
    "editActions": "क्रियाएँ संपादित करें...",
    "editDone": "पूर्ण"
  },
  "id": {
    "copy2clipboard": "Salin ke Papan Klip",
    "post2x": "Posting ke X",
    "post2threds": "Posting ke Threads",
    "post2bluesky": "Posting ke Bluesky",
    "post2mastodon": "Posting ke Mastodon Social",
    "post2linkedin": "Posting ke LinkedIn",
    "post2telegram": "Posting ke Telegram",
    "post2line": "Posting ke LINE",
    "refreshPageInfo": "Muat Ulang Halaman",
    "onError": "Untuk menggunakan ekstensi ini, ekstensi harus diaktifkan sebelum memuat halaman. Silakan coba lagi setelah menyegarkan halaman di Safari.",
    "editActions": "Edit Actions...",
    "editDone": "Selesai"
  },
  "ja": {
    "copy2clipboard": "クリップボードにコピー",
    "post2x": "Xに投稿",
    "post2threds": "Threadsに投稿",
    "post2bluesky": "Blueskyに投稿",
    "post2mastodon": "Mastodon Socialに投稿",
    "post2linkedin": "LinkedInに投稿",
    "post2telegram": "Telegramに投稿",
    "post2line": "LINEに投稿",
    "refreshPageInfo": "ページを再読み込み",
    "onError": "この機能拡張を使用するには、ページを読み込む前に有効化する必要があります。Safariでページを更新してから、再度お試しください。",
    "editActions": "アクションを編集...",
    "editDone": "完了"
  },
  "ko-KR": {
    "copy2clipboard": "클립보드에 복사",
    "post2x": "X에 게시",
    "post2threds": "Threads에 게시",
    "post2bluesky": "Bluesky에 게시",
    "post2mastodon": "Mastodon Social에 게시",
    "post2linkedin": "LinkedIn에 게시",
    "post2telegram": "Telegram에 게시",
    "post2line": "LINE에 게시",
    "refreshPageInfo": "페이지 새로 고침",
    "onError": "이 확장 프로그램을 사용하려면 페이지를 로드하기 전에 활성화되어 있어야 합니다. Safari에서 페이지를 새로 고친 후 다시 시도하세요.",
    "editActions": "작업 편집...",
    "editDone": "완료"
  },
  "nl": {
    "copy2clipboard": "Kopiëren naar klembord",
    "post2x": "Posten op X",
    "post2threds": "Posten op Threads",
    "post2bluesky": "Posten op Bluesky",
    "post2mastodon": "Posten op Mastodon Social",
    "post2linkedin": "Posten op LinkedIn",
    "post2telegram": "Posten op Telegram",
    "post2line": "Posten op LINE",
    "refreshPageInfo": "Pagina herladen",
    "onError": "Om deze extensie te gebruiken, moet deze vóór het laden van de pagina worden ingeschakeld. Probeer het opnieuw nadat u de pagina in Safari hebt vernieuwd.",
    "editActions": "Acties bewerken...",
    "editDone": "Klaar"
  },
  "pt": {
    "copy2clipboard": "Copiar para a área de transferência",
    "post2x": "Postar no X",
    "post2threds": "Postar no Threads",
    "post2bluesky": "Postar no Bluesky",
    "post2mastodon": "Postar no Mastodon Social",
    "post2linkedin": "Postar no LinkedIn",
    "post2telegram": "Postar no Telegram",
    "post2line": "Postar no LINE",
    "refreshPageInfo": "Recarregar página",
    "onError": "Para usar esta extensão, ela deve estar ativada antes de carregar a página. Tente novamente após atualizar a página no Safari.",
    "editActions": "Editar ações...",
    "editDone": "Concluído"
  },
  "pt-PT": {
    "copy2clipboard": "Copiar para a área de transferência",
    "post2x": "Publicar no X",
    "post2threds": "Publicar no Threads",
    "post2bluesky": "Publicar no Bluesky",
    "post2mastodon": "Publicar no Mastodon Social",
    "post2linkedin": "Publicar no LinkedIn",
    "post2telegram": "Publicar no Telegram",
    "post2line": "Publicar no LINE",
    "refreshPageInfo": "Recarregar página",
    "onError": "Para usar esta extensão, ela deve estar ativada antes de carregar a página. Tente novamente após atualizar a página no Safari.",
    "editActions": "Editar ações...",
    "editDone": "Concluído"
  },
  "pt-BR": {
    "copy2clipboard": "Copiar para a área de transferência",
    "post2x": "Publicar no X",
    "post2threds": "Publicar no Threads",
    "post2bluesky": "Publicar no Bluesky",
    "post2mastodon": "Publicar no Mastodon Social",
    "post2linkedin": "Publicar no LinkedIn",
    "post2telegram": "Publicar no Telegram",
    "post2line": "Publicar no LINE",
    "refreshPageInfo": "Recarregar página",
    "onError": "Para usar esta extensão, ela deve estar ativada antes de carregar a página. Tente novamente após atualizar a página no Safari.",
    "editActions": "Editar ações...",
    "editDone": "Concluído"
  },
  "th": {
    "copy2clipboard": "คัดลอกไปยังคลิปบอร์ด",
    "post2x": "โพสต์ไปที่ X",
    "post2threds": "โพสต์ไปที่ Threads",
    "post2bluesky": "โพสต์ไปที่ Bluesky",
    "post2mastodon": "โพสต์ไปที่ Mastodon Social",
    "post2linkedin": "โพสต์ไปที่ LinkedIn",
    "post2telegram": "โพสต์ไปที่ Telegram",
    "post2line": "โพสต์ไปที่ LINE",
    "refreshPageInfo": "รีโหลดหน้าเว็บ",
    "onError": "ในการใช้ส่วนขยายนี้ จำเป็นต้องเปิดใช้งานก่อนโหลดหน้าเว็บ กรุณากดปุ่มด้านล่างเพื่อทดลองอีกครั้งหลังจากที่อัปเดตหน้าใน Safari",
    "editActions": "แก้ไขการกระทำ...",
    "editDone": "เสร็จสิ้น"
  },
  "tr": {
    "copy2clipboard": "Panoya Kopyala",
    "post2x": "X'e Gönder",
    "post2threds": "Threads'e Gönder",
    "post2bluesky": "Bluesky'e Gönder",
    "post2mastodon": "Mastodon Social'e Gönder",
    "post2linkedin": "LinkedIn'e Gönder",
    "post2telegram": "Telegram'a Gönder",
    "post2line": "LINE'a Gönder",
    "refreshPageInfo": "Sayfayı Yenile",
    "onError": "Bu uzantıyı kullanmak için, sayfayı yüklemeden önce etkinleştirilmiş olmalıdır. Safari'de sayfayı yeniledikten sonra tekrar deneyin.",
    "editActions": "Eylemleri Düzenle...",
    "editDone": "Tamamlandı"
  },
  "zh": {
    "copy2clipboard": "复制到剪贴板",
    "post2x": "发布到X",
    "post2threds": "发布到Threads",
    "post2bluesky": "发布到BlueSky",
    "post2mastodon": "发布到Mastodon Social",
    "post2linkedin": "发布到LinkedIn",
    "post2telegram": "发布到Telegram",
    "post2line": "发布到LINE",
    "refreshPageInfo": "重新加载页面",
    "onError": "要使用此扩展程序，必须在加载页面之前启用。请在Safari中刷新页面后重试。",
    "editActions": "编辑操作...",
    "editDone": "完成"
  },
  "zh-CN": {
    "copy2clipboard": "复制到剪贴板",
    "post2x": "发布到X",
    "post2threds": "发布到Threads",
    "post2bluesky": "发布到BlueSky",
    "post2mastodon": "发布到Mastodon Social",
    "post2linkedin": "发布到LinkedIn",
    "post2telegram": "发布到Telegram",
    "post2line": "发布到LINE",
    "refreshPageInfo": "重新加载页面",
    "onError": "要使用此扩展程序，必须在加载页面之前启用。请在Safari中刷新页面后重试。",
    "editActions": "编辑操作...",
    "editDone": "完成"
  },
  "zh-TW": {
    "copy2clipboard": "複製到剪貼簿",
    "post2x": "發佈到X",
    "post2threds": "發佈到Threads",
    "post2bluesky": "發佈到BlueSky",
    "post2mastodon": "發佈到Mastodon Social",
    "post2linkedin": "發佈到LinkedIn",
    "post2telegram": "發佈到Telegram",
    "post2line": "發佈到LINE",
    "refreshPageInfo": "重新載入頁面",
    "onError": "要使用此擴充功能，必須在載入頁面之前啟用。請在Safari中重新載入頁面後再試一次。",
    "editActions": "編輯操作...",
    "editDone": "完成"
  },
  "zh-HK": {
    "copy2clipboard": "複製到剪貼簿",
    "post2x": "發佈到X",
    "post2threds": "發佈到Threads",
    "post2bluesky": "發佈到BlueSky",
    "post2mastodon": "發佈到Mastodon Social",
    "post2linkedin": "發佈到LinkedIn",
    "post2telegram": "發佈到Telegram",
    "post2line": "發佈到LINE",
    "refreshPageInfo": "重新載入頁面",
    "onError": "要使用此擴充功能，必須在載入頁面之前啟用。請在Safari中重新載入頁面後再試一次。",
    "editActions": "編輯操作...",
    "editDone": "完成"
  },
};

export const getCurrentLangCode = () => {
  const langCode = window.navigator.language || 'en';

  return labelStrings[langCode]
    ? langCode
    : (labelStrings[langCode.substring(0, 2)] ? langCode.substring(0, 2) : 'en');
};
