const labelStrings = {
  "en": {
    "copy2clipboard": "Copy to Clipboard",
    "sharelink": "Share...",
    "post2x": "Post to X",
    "post2threads": "Post to Threads",
    "post2bluesky": "Post to Bluesky",
    "post2mastodon": "Post to Mastodon Social",
    "post2linkedin": "Post to LinkedIn",
    "post2telegram": "Post to Telegram",
    "post2line": "Post to LINE",
    "post2tumblr": "Post to Tumblr",
    "post2vk": "Post to VK",
    "post2weibo": "Post to Weibo",
    "post2chatgpt": "Post to ChatGPT",
    "post2claude": "Post to Claude",
    "onError": "To use this extension, it must be enabled before loading the page. Please try again after refreshing the page in Safari.",
    "settings": "Settings",
    "quoteStyleSetting": "Quotes",
    "editActions": "Edit Actions...",
    "editDone": "Done",
    "tooltip": {
      "toggleBullet": "Click to toggle",
      "dragItem": "Drag to reorder"
    }
  },
  "ar": {
    "copy2clipboard": "نسخ إلى الحافظة",
    "sharelink": "مشاركة...",
    "post2x": "نشر على X",
    "post2threads": "نشر على Threads",
    "post2bluesky": "نشر على Bluesky",
    "post2mastodon": "نشر على Mastodon Social",
    "post2linkedin": "نشر على LinkedIn",
    "post2telegram": "نشر على Telegram",
    "post2line": "نشر على LINE",
    "post2tumblr": "نشر على Tumblr",
    "post2vk": "نشر على VK",
    "post2weibo": "نشر على Weibo",
    "post2chatgpt": "نشر على ChatGPT",
    "post2claude": "نشر على Claude",
    "onError": "لاستخدام هذا الامتداد، يجب تفعيله قبل تحميل الصفحة. بعد تحديث الصفحة في Safari، حاول مرة أخرى.",
    "settings": "الإعدادات",
    "quoteStyleSetting": "اقتباس",
    "editActions": "تحرير الإجراءات...",
    "editDone": "تم",
    "tooltip": {
      "toggleBullet": "انقر للتبديل",
      "dragItem": "اسحب لإعادة الترتيب"
    }
  },
  "ar-SA": {
    "copy2clipboard": "نسخ إلى الحافظة",
    "sharelink": "مشاركة...",
    "post2x": "نشر على X",
    "post2threads": "نشر على Threads",
    "post2bluesky": "نشر على Bluesky",
    "post2mastodon": "نشر على Mastodon Social",
    "post2linkedin": "نشر على LinkedIn",
    "post2telegram": "نشر على Telegram",
    "post2line": "نشر على LINE",
    "post2tumblr": "نشر على Tumblr",
    "post2vk": "نشر على VK",
    "post2weibo": "نشر على Weibo",
    "post2chatgpt": "نشر على ChatGPT",
    "post2claude": "نشر على Claude",
    "onError": "لاستخدام هذا الامتداد، يجب تفعيله قبل تحميل الصفحة. بعد تحديث الصفحة في Safari، حاول مرة أخرى.",
    "settings": "الإعدادات",
    "quoteStyleSetting": "اقتباس",
    "editActions": "تحرير الإجراءات...",
    "editDone": "تم",
    "tooltip": {
      "toggleBullet": "انقر للتبديل",
      "dragItem": "اسحب لإعادة الترتيب"
    }
  },
  "ca": {
    "copy2clipboard": "Copiar al portapapers",
    "sharelink": "Compartir...",
    "post2x": "Publicar a X",
    "post2threads": "Publicar a Threads",
    "post2bluesky": "Publicar a Bluesky",
    "post2mastodon": "Publicar a Mastodon Social",
    "post2linkedin": "Publicar a LinkedIn",
    "post2telegram": "Publicar a Telegram",
    "post2line": "Publicar a LINE",
    "post2tumblr": "Publicar a Tumblr",
    "post2vk": "Publicar a VK",
    "post2weibo": "Publicar a Weibo",
    "post2chatgpt": "Publicar a ChatGPT",
    "post2claude": "Publicar a Claude",
    "onError": "Per utilitzar aquesta extensió, ha d'estar activada abans de carregar la pàgina. Torneu-ho a intentar després d'actualitzar la pàgina a Safari.",
    "settings": "Configuració",
    "quoteStyleSetting": "Cometes",
    "editActions": "Editar accions...",
    "editDone": "Fet",
    "tooltip": {
      "toggleBullet": "Feu clic per alternar",
      "dragItem": "Arrossegueu per reordenar"
    }
  },
  "cs": {
    "copy2clipboard": "Kopírovat do schránky",
    "sharelink": "Sdílet...",
    "post2x": "Odeslat na X",
    "post2threads": "Odeslat na Threads",
    "post2bluesky": "Odeslat na Bluesky",
    "post2mastodon": "Odeslat na Mastodon Social",
    "post2linkedin": "Odeslat na LinkedIn",
    "post2telegram": "Odeslat na Telegram",
    "post2line": "Odeslat na LINE",
    "post2tumblr": "Odeslat na Tumblr",
    "post2vk": "Odeslat na VK",
    "post2weibo": "Odeslat na Weibo",
    "post2chatgpt": "Odeslat na ChatGPT",
    "post2claude": "Odeslat na Claude",
    "onError": "Pro použití tohoto rozšíření musí být aktivováno před načtením stránky. Zkuste to znovu po obnovení stránky v Safari.",
    "settings": "Nastavení",
    "quoteStyleSetting": "Uvozovky",
    "editActions": "Upravit akce...",
    "editDone": "Hotovo",
    "tooltip": {
      "toggleBullet": "Kliknutím přepnete",
      "dragItem": "Přetáhněte pro změnu pořadí"
    }
  },
  "da": {
    "copy2clipboard": "Kopier til udklipsholder",
    "sharelink": "Del...",
    "post2x": "Post til X",
    "post2threads": "Post til Threads",
    "post2bluesky": "Post til Bluesky",
    "post2mastodon": "Post til Mastodon Social",
    "post2linkedin": "Post til LinkedIn",
    "post2telegram": "Post til Telegram",
    "post2line": "Post til LINE",
    "post2tumblr": "Post til Tumblr",
    "post2vk": "Post til VK",
    "post2weibo": "Post til Weibo",
    "post2chatgpt": "Post til ChatGPT",
    "post2claude": "Post til Claude",
    "onError": "For at bruge denne udvidelse skal den være aktiveret, før siden indlæses. Prøv igen efter at have opdateret siden i Safari.",
    "settings": "Indstillinger",
    "quoteStyleSetting": "Anførsel",
    "editActions": "Rediger handlinger...",
    "editDone": "Færdig",
    "tooltip": {
      "toggleBullet": "Klik for at skifte",
      "dragItem": "Træk for at ændre rækkefølge"
    }
  },
  "de": {
    "copy2clipboard": "In die Zwischenablage kopieren",
    "sharelink": "Teilen...",
    "post2x": "Auf X posten",
    "post2threads": "Auf Threads posten",
    "post2bluesky": "Auf Bluesky posten",
    "post2mastodon": "Auf Mastodon Social posten",
    "post2linkedin": "Auf LinkedIn posten",
    "post2telegram": "Auf Telegram posten",
    "post2line": "Auf LINE posten",
    "post2tumblr": "Auf Tumblr posten",
    "post2vk": "Auf VK posten",
    "post2weibo": "Auf Weibo posten",
    "post2chatgpt": "Auf ChatGPT posten",
    "post2claude": "Auf Claude posten",
    "onError": "Um diese Erweiterung zu verwenden, muss sie vor dem Laden der Seite aktiviert werden. Bitte versuchen Sie es erneut, nachdem Sie die Seite in Safari aktualisiert haben.",
    "settings": "Einstellungen",
    "quoteStyleSetting": "Anführung",
    "editActions": "Aktionen bearbeiten...",
    "editDone": "Fertig",
    "tooltip": {
      "toggleBullet": "Klicken zum Umschalten",
      "dragItem": "Ziehen zum Neuordnen"
    }
  },
  "el": {
    "copy2clipboard": "Αντιγραφή στο πρόχειρο",
    "sharelink": "Κοινή χρήση...",
    "post2x": "Δημοσίευση στο X",
    "post2threads": "Δημοσίευση στα Threads",
    "post2bluesky": "Δημοσίευση στο Bluesky",
    "post2mastodon": "Δημοσίευση στο Mastodon Social",
    "post2linkedin": "Δημοσίευση στο LinkedIn",
    "post2telegram": "Δημοσίευση στο Telegram",
    "post2line": "Δημοσίευση στο LINE",
    "post2tumblr": "Δημοσίευση στο Tumblr",
    "post2vk": "Δημοσίευση στο VK",
    "post2weibo": "Δημοσίευση στο Weibo",
    "post2chatgpt": "Δημοσίευση στο ChatGPT",
    "post2claude": "Δημοσίευση στο Claude",
    "onError": "Για να χρησιμοποιήσετε αυτήν την επέκταση, πρέπει να είναι ενεργοποιημένη πριν από την φόρτωση της σελίδας. Δοκιμάστε ξανά μετά την ανανέωση της σελίδας στο Safari.",
    "settings": "Ρυθμίσεις",
    "quoteStyleSetting": "Εισαγωγικά",
    "editActions": "Επεξεργασία ενεργειών...",
    "editDone": "Έγινε",
    "tooltip": {
      "toggleBullet": "Κάντε κλικ για εναλλαγή",
      "dragItem": "Σύρετε για αναδιάταξη"
    }
  },
  "en-GB": {
    "copy2clipboard": "Copy to Clipboard",
    "sharelink": "Share...",
    "post2x": "Post to X",
    "post2threads": "Post to Threads",
    "post2bluesky": "Post to Bluesky",
    "post2mastodon": "Post to Mastodon Social",
    "post2linkedin": "Post to LinkedIn",
    "post2telegram": "Post to Telegram",
    "post2line": "Post to LINE",
    "post2tumblr": "Post to Tumblr",
    "post2vk": "Post to VK",
    "post2weibo": "Post to Weibo",
    "post2chatgpt": "Post to ChatGPT",
    "post2claude": "Post to Claude",
    "onError": "To use this extension, it must be enabled before loading the page. Please try again after refreshing the page in Safari.",
    "settings": "Settings",
    "quoteStyleSetting": "Quotes",
    "editActions": "Edit Actions...",
    "editDone": "Done",
    "tooltip": {
      "toggleBullet": "Click to toggle",
      "dragItem": "Drag to reorder"
    }
  },
  "en-AU": {
    "copy2clipboard": "Copy to Clipboard",
    "sharelink": "Share...",
    "post2x": "Post to X",
    "post2threads": "Post to Threads",
    "post2bluesky": "Post to Bluesky",
    "post2mastodon": "Post to Mastodon Social",
    "post2linkedin": "Post to LinkedIn",
    "post2telegram": "Post to Telegram",
    "post2line": "Post to LINE",
    "post2tumblr": "Post to Tumblr",
    "post2vk": "Post to VK",
    "post2weibo": "Post to Weibo",
    "post2chatgpt": "Post to ChatGPT",
    "post2claude": "Post to Claude",
    "onError": "To use this extension, it must be enabled before loading the page. Please try again after refreshing the page in Safari.",
    "settings": "Settings",
    "quoteStyleSetting": "Quotes",
    "editActions": "Edit Actions...",
    "editDone": "Done",
    "tooltip": {
      "toggleBullet": "Click to toggle",
      "dragItem": "Drag to reorder"
    }
  },
  "en-CA": {
    "copy2clipboard": "Copy to Clipboard",
    "sharelink": "Share...",
    "post2x": "Post to X",
    "post2threads": "Post to Threads",
    "post2bluesky": "Post to Bluesky",
    "post2mastodon": "Post to Mastodon Social",
    "post2linkedin": "Post to LinkedIn",
    "post2telegram": "Post to Telegram",
    "post2line": "Post to LINE",
    "post2tumblr": "Post to Tumblr",
    "post2vk": "Post to VK",
    "post2weibo": "Post to Weibo",
    "post2chatgpt": "Post to ChatGPT",
    "post2claude": "Post to Claude",
    "onError": "To use this extension, it must be enabled before loading the page. Please try again after refreshing the page in Safari.",
    "settings": "Settings",
    "quoteStyleSetting": "Quotes",
    "editActions": "Edit Actions...",
    "editDone": "Done",
    "tooltip": {
      "toggleBullet": "Click to toggle",
      "dragItem": "Drag to reorder"
    }
  },
  "es": {
    "copy2clipboard": "Copiar al portapapeles",
    "sharelink": "Compartir...",
    "post2x": "Publicar en X",
    "post2threads": "Publicar en Threads",
    "post2bluesky": "Publicar en Bluesky",
    "post2mastodon": "Publicar en Mastodon Social",
    "post2linkedin": "Publicar en LinkedIn",
    "post2telegram": "Publicar en Telegram",
    "post2line": "Publicar en LINE",
    "post2tumblr": "Publicar en Tumblr",
    "post2vk": "Publicar en VK",
    "post2weibo": "Publicar en Weibo",
    "post2chatgpt": "Publicar en ChatGPT",
    "post2claude": "Publicar en Claude",
    "onError": "Para usar esta extensión, debe estar habilitada antes de cargar la página. Intenta de nuevo después de actualizar la página en Safari.",
    "settings": "Configuración",
    "quoteStyleSetting": "Comillas",
    "editActions": "Editar acciones...",
    "editDone": "Hecho",
    "tooltip": {
      "toggleBullet": "Clic para alternar",
      "dragItem": "Arrastrar para reordenar"
    }
  },
  "es-MX": {
    "copy2clipboard": "Copiar al portapapeles",
    "sharelink": "Compartir...",
    "post2x": "Publicar en X",
    "post2threads": "Publicar en Threads",
    "post2bluesky": "Publicar en Bluesky",
    "post2mastodon": "Publicar en Mastodon Social",
    "post2linkedin": "Publicar en LinkedIn",
    "post2telegram": "Publicar en Telegram",
    "post2line": "Publicar en LINE",
    "post2tumblr": "Publicar en Tumblr",
    "post2vk": "Publicar en VK",
    "post2weibo": "Publicar en Weibo",
    "post2chatgpt": "Publicar en ChatGPT",
    "post2claude": "Publicar en Claude",
    "onError": "Para usar esta extensión, debe estar habilitada antes de cargar la página. Intenta de nuevo después de actualizar la página en Safari.",
    "settings": "Configuración",
    "quoteStyleSetting": "Comillas",
    "editActions": "Editar acciones...",
    "editDone": "Hecho",
    "tooltip": {
      "toggleBullet": "Clic para alternar",
      "dragItem": "Arrastrar para reordenar"
    }
  },
  "fi": {
    "copy2clipboard": "Kopioi leikepöydälle",
    "sharelink": "Jaa...",
    "post2x": "Julkaise X:ssä",
    "post2threads": "Julkaise Threadsissä",
    "post2bluesky": "Julkaise Blueskyssä",
    "post2mastodon": "Julkaise Mastodon Socialissa",
    "post2linkedin": "Julkaise LinkedIn:ssä",
    "post2telegram": "Julkaise Telegramissa",
    "post2line": "Julkaise LINE:ssä",
    "post2tumblr": "Julkaise Tumblr:ssä",
    "post2vk": "Julkaise VK:ssä",
    "post2weibo": "Julkaise Weibo:ssä",
    "post2chatgpt": "Julkaise ChatGPT:ssä",
    "post2claude": "Julkaise Claude:ssä",
    "onError": "Jotta voit käyttää tätä laajennusta, se on otettava käyttöön ennen sivun lataamista. Yritä uudelleen, kun olet päivittänyt sivun Safarissa.",
    "settings": "Asetukset",
    "quoteStyleSetting": "Lainaus",
    "editActions": "Muokkaa toimintoja...",
    "editDone": "Valmis",
    "tooltip": {
      "toggleBullet": "Napsauta vaihtaaksesi",
      "dragItem": "Vedä järjestääksesi uudelleen"
    }
  },
  "fr": {
    "copy2clipboard": "Copier dans le presse-papiers",
    "sharelink": "Partager...",
    "post2x": "Publier sur X",
    "post2threads": "Publier sur Threads",
    "post2bluesky": "Publier sur Bluesky",
    "post2mastodon": "Publier sur Mastodon Social",
    "post2linkedin": "Publier sur LinkedIn",
    "post2telegram": "Publier sur Telegram",
    "post2line": "Publier sur LINE",
    "post2tumblr": "Publier sur Tumblr",
    "post2vk": "Publier sur VK",
    "post2weibo": "Publier sur Weibo",
    "post2chatgpt": "Publier sur ChatGPT",
    "post2claude": "Publier sur Claude",
    "onError": "Pour utiliser cette extension, elle doit être activée avant de charger la page. Veuillez réessayer après avoir actualisé la page dans Safari.",
    "settings": "Réglages",
    "quoteStyleSetting": "Guillemets",
    "editActions": "Modifier les actions...",
    "editDone": "Terminé",
    "tooltip": {
      "toggleBullet": "Cliquer pour basculer",
      "dragItem": "Faire glisser pour réorganiser"
    }
  },
  "fr-CA": {
    "copy2clipboard": "Copier dans le presse-papiers",
    "sharelink": "Partager...",
    "post2x": "Publier sur X",
    "post2threads": "Publier sur Threads",
    "post2bluesky": "Publier sur Bluesky",
    "post2mastodon": "Publier sur Mastodon Social",
    "post2linkedin": "Publier sur LinkedIn",
    "post2telegram": "Publier sur Telegram",
    "post2line": "Publier sur LINE",
    "post2tumblr": "Publier sur Tumblr",
    "post2vk": "Publier sur VK",
    "post2weibo": "Publier sur Weibo",
    "post2chatgpt": "Publier sur ChatGPT",
    "post2claude": "Publier sur Claude",
    "onError": "Pour utiliser cette extension, elle doit être activée avant de charger la page. Veuillez réessayer après avoir actualisé la page dans Safari.",
    "settings": "Réglages",
    "quoteStyleSetting": "Guillemets",
    "editActions": "Modifier les actions...",
    "editDone": "Terminé",
    "tooltip": {
      "toggleBullet": "Cliquer pour basculer",
      "dragItem": "Faire glisser pour réorganiser"
    }
  },
  "hu": {
    "copy2clipboard": "Másolás a vágólapra",
    "sharelink": "Megosztás...",
    "post2x": "Közzététel az X-en",
    "post2threads": "Közzététel a Threads-en",
    "post2bluesky": "Közzététel a Bluesky-n",
    "post2mastodon": "Közzététel a Mastodon Social-on",
    "post2linkedin": "Közzététel a LinkedIn-en",
    "post2telegram": "Közzététel a Telegram-on",
    "post2line": "Közzététel a LINE-on",
    "post2tumblr": "Közzététel a Tumblr-on",
    "post2vk": "Közzététel a VK-on",
    "post2weibo": "Közzététel a Weibo-on",
    "post2chatgpt": "Közzététel a ChatGPT-n",
    "post2claude": "Közzététel a Claude-on",
    "onError": "Ahhoz, hogy ezt az alkalmazást használni tudja, engedélyezni kell az oldal betöltése előtt. Kérjük, próbálja újra az oldal Safari-ban történő frissítése után.",
    "settings": "Beállítások",
    "quoteStyleSetting": "Idézőjel",
    "editActions": "Akciók szerkesztése...",
    "editDone": "Kész",
    "tooltip": {
      "toggleBullet": "Kattintson a váltáshoz",
      "dragItem": "Húzza az átrendezéshez"
    }
  },
  "he": {
    "copy2clipboard": "העתק ללוח",
    "sharelink": "שתף...",
    "post2x": "פרסם ל-X",
    "post2threads": "פרסם ל-Threads",
    "post2bluesky": "פרסם ל-Bluesky",
    "post2mastodon": "פרסם ל-Mastodon Social",
    "post2linkedin": "פרסם ל-LinkedIn",
    "post2telegram": "פרסם ל-Telegram",
    "post2line": "פרסם ל-LINE",
    "post2tumblr": "פרסם ל-Tumblr",
    "post2vk": "פרסם ל-VK",
    "post2weibo": "פרסם ל-Weibo",
    "post2chatgpt": "פרסם ל-ChatGPT",
    "post2claude": "פרסם ל-Claude",
    "onError": "כדי להשתמש בתוסף זה, יש להפעיל אותו לפני טעינת הדף. אנא נסה שוב לאחר רענון הדף ב-Safari.",
    "settings": "הגדרות",
    "quoteStyleSetting": "מרכאות",
    "editActions": "ערוך פעולות...",
    "editDone": "סיים",
    "tooltip": {
      "toggleBullet": "לחץ כדי להחליף",
      "dragItem": "גרור כדי לסדר מחדש"
    }
  },
  "hr": {
    "copy2clipboard": "Kopiraj u međuspremnik",
    "sharelink": "Podijeli...",
    "post2x": "Objavi na X",
    "post2threads": "Objavi na Threads",
    "post2bluesky": "Objavi na Bluesky",
    "post2mastodon": "Objavi na Mastodon Social",
    "post2linkedin": "Objavi na LinkedIn",
    "post2telegram": "Objavi na Telegram",
    "post2line": "Objavi na LINE",
    "post2tumblr": "Objavi na Tumblr",
    "post2vk": "Objavi na VK",
    "post2weibo": "Objavi na Weibo",
    "post2chatgpt": "Objavi na ChatGPT",
    "post2claude": "Objavi na Claude",
    "onError": "Da biste koristili ovu ekstenziju, mora biti omogućena prije učitavanja stranice. Pokušajte ponovo nakon što osvježite stranicu u Safariju.",
    "settings": "Postavke",
    "quoteStyleSetting": "Navodnici",
    "editActions": "Uredi radnje...",
    "editDone": "Gotovo",
    "tooltip": {
      "toggleBullet": "Kliknite za prebacivanje",
      "dragItem": "Povucite za promjenu redoslijeda"
    }
  },
  "hi": {
    "copy2clipboard": "क्लिपबोर्ड में कॉपी करें",
    "sharelink": "साझा करें...",
    "post2x": "X पर पोस्ट करें",
    "post2threads": "Threads पर पोस्ट करें",
    "post2bluesky": "Bluesky पर पोस्ट करें",
    "post2mastodon": "Mastodon Social पर पोस्ट करें",
    "post2linkedin": "LinkedIn पर पोस्ट करें",
    "post2telegram": "Telegram पर पोस्ट करें",
    "post2line": "LINE पर पोस्ट करें",
    "post2tumblr": "Tumblr पर पोस्ट करें",
    "post2vk": "VK पर पोस्ट करें",
    "post2weibo": "Weibo पर पोस्ट करें",
    "post2chatgpt": "ChatGPT पर पोस्ट करें",
    "post2claude": "Claude पर पोस्ट करें",
    "onError": "इस एक्सटेंशन का उपयोग करने के लिए, इसे पेज लोड करने से पहले सक्षम करना होगा। सफारी में पेज को रीफ्रेश करने के बाद फिर से प्रयास करें।",
    "settings": "सेटिंग्स",
    "quoteStyleSetting": "उद्धरण",
    "editActions": "क्रियाएँ संपादित करें...",
    "editDone": "पूर्ण",
    "tooltip": {
      "toggleBullet": "टॉगल करने के लिए क्लिक करें",
      "dragItem": "पुनर्व्यवस्थित करने के लिए खींचें"
    }
  },
  "id": {
    "copy2clipboard": "Salin ke Papan Klip",
    "sharelink": "Bagikan...",
    "post2x": "Posting ke X",
    "post2threads": "Posting ke Threads",
    "post2bluesky": "Posting ke Bluesky",
    "post2mastodon": "Posting ke Mastodon Social",
    "post2linkedin": "Posting ke LinkedIn",
    "post2telegram": "Posting ke Telegram",
    "post2line": "Posting ke LINE",
    "post2tumblr": "Posting ke Tumblr",
    "post2vk": "Posting ke VK",
    "post2weibo": "Posting ke Weibo",
    "post2chatgpt": "Posting ke ChatGPT",
    "post2claude": "Posting ke Claude",
    "onError": "Untuk menggunakan ekstensi ini, ekstensi harus diaktifkan sebelum memuat halaman. Silakan coba lagi setelah menyegarkan halaman di Safari.",
    "settings": "Pengaturan",
    "quoteStyleSetting": "Kutip",
    "editActions": "Edit Tindakan...",
    "editDone": "Selesai",
    "tooltip": {
      "toggleBullet": "Klik untuk beralih",
      "dragItem": "Seret untuk mengatur ulang"
    }
  },
  "it": {
    "copy2clipboard": "Copia negli Appunti",
    "sharelink": "Condividi...",
    "post2x": "Pubblica su X",
    "post2threads": "Pubblica su Threads",
    "post2bluesky": "Pubblica su Bluesky",
    "post2mastodon": "Pubblica su Mastodon Social",
    "post2linkedin": "Pubblica su LinkedIn",
    "post2telegram": "Pubblica su Telegram",
    "post2line": "Pubblica su LINE",
    "post2tumblr": "Pubblica su Tumblr",
    "post2vk": "Pubblica su VK",
    "post2weibo": "Pubblica su Weibo",
    "post2chatgpt": "Pubblica su ChatGPT",
    "post2claude": "Pubblica su Claude",
    "onError": "Per utilizzare questa estensione, deve essere abilitata prima di caricare la pagina. Per favore, riprova dopo aver aggiornato la pagina in Safari.",
    "settings": "Impostazioni",
    "quoteStyleSetting": "Virgolette",
    "editActions": "Modifica Azioni...",
    "editDone": "Fatto",
    "tooltip": {
      "toggleBullet": "Clicca per attivare/disattivare",
      "dragItem": "Trascina per riordinare"
    }
  },
  "ja": {
    "copy2clipboard": "クリップボードにコピー",
    "sharelink": "共有...",
    "post2x": "X に投稿",
    "post2threads": "Threads に投稿",
    "post2bluesky": "Bluesky に投稿",
    "post2mastodon": "Mastodon Social に投稿",
    "post2linkedin": "LinkedIn に投稿",
    "post2telegram": "Telegram に投稿",
    "post2line": "LINE に投稿",
    "post2tumblr": "Tumblr に投稿",
    "post2vk": "VK に投稿",
    "post2weibo": "Weibo に投稿",
    "post2chatgpt": "ChatGPT に投稿",
    "post2claude": "Claude に投稿",
    "onError": "この機能拡張を使用するには、ページを読み込む前に有効化する必要があります。Safari でページを更新してから、再度お試しください。",
    "settings": "設定",
    "quoteStyleSetting": "引用符",
    "editActions": "アクションを編集...",
    "editDone": "完了",
    "tooltip": {
      "toggleBullet": "クリックして切り替え",
      "dragItem": "ドラッグして並べ替え"
    }
  },
  "ko-KR": {
    "copy2clipboard": "클립보드에 복사",
    "sharelink": "공유...",
    "post2x": "X 에 게시",
    "post2threads": "Threads 에 게시",
    "post2bluesky": "Bluesky 에 게시",
    "post2mastodon": "Mastodon Social 에 게시",
    "post2linkedin": "LinkedIn 에 게시",
    "post2telegram": "Telegram 에 게시",
    "post2line": "LINE 에 게시",
    "post2tumblr": "Tumblr 에 게시",
    "post2vk": "VK 에 게시",
    "post2weibo": "Weibo 에 게시",
    "post2chatgpt": "ChatGPT 에 게시",
    "post2claude": "Claude 에 게시",
    "onError": "이 확장 프로그램을 사용하려면 페이지를 로드하기 전에 활성화되어 있어야 합니다. Safari 에서 페이지를 새로 고친 후 다시 시도하세요.",
    "settings": "설정",
    "quoteStyleSetting": "따옴표",
    "editActions": "동작 편집...",
    "editDone": "완료",
    "tooltip": {
      "toggleBullet": "클릭하여 전환",
      "dragItem": "드래그하여 순서 변경"
    }
  },
  "ms": {
    "copy2clipboard": "Salin ke Papan Klip",
    "sharelink": "Kongsi...",
    "post2x": "Kongsi di X",
    "post2threads": "Kongsi di Threads",
    "post2bluesky": "Kongsi di Bluesky",
    "post2mastodon": "Kongsi di Mastodon Social",
    "post2linkedin": "Kongsi di LinkedIn",
    "post2telegram": "Kongsi di Telegram",
    "post2line": "Kongsi di LINE",
    "post2tumblr": "Kongsi di Tumblr",
    "post2vk": "Kongsi di VK",
    "post2weibo": "Kongsi di Weibo",
    "post2chatgpt": "Kongsi di ChatGPT",
    "post2claude": "Kongsi di Claude",
    "onError": "Untuk menggunakan sambungan ini, ia mesti diaktifkan sebelum memuatkan halaman. Sila cuba lagi selepas menyegarkan halaman di Safari.",
    "settings": "Tetapan",
    "quoteStyleSetting": "Petik",
    "editActions": "Edit Tindakan...",
    "editDone": "Selesai",
    "tooltip": {
      "toggleBullet": "Klik untuk togol",
      "dragItem": "Seret untuk menyusun semula"
    }
  },
  "nb": {
    "copy2clipboard": "Kopier til utklippstavle",
    "sharelink": "Del...",
    "post2x": "Legg ut til X",
    "post2threads": "Legg ut til Threads",
    "post2bluesky": "Legg ut til Bluesky",
    "post2mastodon": "Legg ut til Mastodon Social",
    "post2linkedin": "Legg ut til LinkedIn",
    "post2telegram": "Legg ut til Telegram",
    "post2line": "Legg ut til LINE",
    "post2tumblr": "Legg ut til Tumblr",
    "post2vk": "Legg ut til VK",
    "post2weibo": "Legg ut til Weibo",
    "post2chatgpt": "Legg ut til ChatGPT",
    "post2claude": "Legg ut til Claude",
    "onError": "For å bruke denne utvidelsen må den være aktivert før siden lastes. Prøv igjen etter å ha oppdatert siden i Safari.",
    "settings": "Innstillinger",
    "quoteStyleSetting": "Anførselstegn",
    "editActions": "Rediger handlinger...",
    "editDone": "Ferdig",
    "tooltip": {
      "toggleBullet": "Klikk for å veksle",
      "dragItem": "Dra for å endre rekkefølge"
    }
  },
  "nl": {
    "copy2clipboard": "Kopiëren naar klembord",
    "sharelink": "Delen...",
    "post2x": "Posten op X",
    "post2threads": "Posten op Threads",
    "post2bluesky": "Posten op Bluesky",
    "post2mastodon": "Posten op Mastodon Social",
    "post2linkedin": "Posten op LinkedIn",
    "post2telegram": "Posten op Telegram",
    "post2line": "Posten op LINE",
    "post2tumblr": "Posten op Tumblr",
    "post2vk": "Posten op VK",
    "post2weibo": "Posten op Weibo",
    "post2chatgpt": "Posten op ChatGPT",
    "post2claude": "Posten op Claude",
    "onError": "Om deze extensie te gebruiken, moet deze vóór het laden van de pagina worden ingeschakeld. Probeer het opnieuw nadat u de pagina in Safari hebt vernieuwd.",
    "settings": "Instellingen",
    "quoteStyleSetting": "Aanhalings",
    "editActions": "Acties bewerken...",
    "editDone": "Klaar",
    "tooltip": {
      "toggleBullet": "Klik om te schakelen",
      "dragItem": "Sleep om te herschikken"
    }
  },
  "pl": {
    "copy2clipboard": "Skopiuj do schowka",
    "sharelink": "Udostępnij...",
    "post2x": "Opublikuj na X",
    "post2threads": "Opublikuj na Threads",
    "post2bluesky": "Opublikuj na Bluesky",
    "post2mastodon": "Opublikuj na Mastodon Social",
    "post2linkedin": "Opublikuj na LinkedIn",
    "post2telegram": "Opublikuj na Telegram",
    "post2line": "Opublikuj na LINE",
    "post2tumblr": "Opublikuj na Tumblr",
    "post2vk": "Opublikuj na VK",
    "post2weibo": "Opublikuj na Weibo",
    "post2chatgpt": "Opublikuj na ChatGPT",
    "post2claude": "Opublikuj na Claude",
    "onError": "Aby użyć tego rozszerzenia, musi być ono włączone przed załadowaniem strony. Spróbuj ponownie po odświeżeniu strony w Safari.",
    "settings": "Ustawienia",
    "quoteStyleSetting": "Cudzysłowy",
    "editActions": "Edytuj akcje...",
    "editDone": "Gotowe",
    "tooltip": {
      "toggleBullet": "Kliknij, aby przełączyć",
      "dragItem": "Przeciągnij, aby zmienić kolejność"
    }
  },
  "pt": {
    "copy2clipboard": "Copiar para a área de transferência",
    "sharelink": "Partilhar...",
    "post2x": "Postar no X",
    "post2threads": "Postar no Threads",
    "post2bluesky": "Postar no Bluesky",
    "post2mastodon": "Postar no Mastodon Social",
    "post2linkedin": "Postar no LinkedIn",
    "post2telegram": "Postar no Telegram",
    "post2line": "Postar no LINE",
    "post2tumblr": "Postar no Tumblr",
    "post2vk": "Postar no VK",
    "post2weibo": "Postar no Weibo",
    "post2chatgpt": "Postar no ChatGPT",
    "post2claude": "Postar no Claude",
    "onError": "Para usar esta extensão, ela deve estar ativada antes de carregar a página. Tente novamente após atualizar a página no Safari.",
    "settings": "Configurações",
    "quoteStyleSetting": "Aspas",
    "editActions": "Editar ações...",
    "editDone": "Concluído",
    "tooltip": {
      "toggleBullet": "Clique para alternar",
      "dragItem": "Arraste para reordenar"
    }
  },
  "pt-PT": {
    "copy2clipboard": "Copiar para a área de transferência",
    "sharelink": "Partilhar...",
    "post2x": "Publicar no X",
    "post2threads": "Publicar no Threads",
    "post2bluesky": "Publicar no Bluesky",
    "post2mastodon": "Publicar no Mastodon Social",
    "post2linkedin": "Publicar no LinkedIn",
    "post2telegram": "Publicar no Telegram",
    "post2line": "Publicar no LINE",
    "post2tumblr": "Publicar no Tumblr",
    "post2vk": "Publicar no VK",
    "post2weibo": "Publicar no Weibo",
    "post2chatgpt": "Publicar no ChatGPT",
    "post2claude": "Publicar no Claude",
    "onError": "Para usar esta extensão, ela deve estar ativada antes de carregar a página. Tente novamente após atualizar a página no Safari.",
    "settings": "Definições",
    "quoteStyleSetting": "Aspas",
    "editActions": "Editar ações...",
    "editDone": "Concluído",
    "tooltip": {
      "toggleBullet": "Clique para alternar",
      "dragItem": "Arraste para reordenar"
    }
  },
  "pt-BR": {
    "copy2clipboard": "Copiar para a área de transferência",
    "sharelink": "Compartilhar...",
    "post2x": "Publicar no X",
    "post2threads": "Publicar no Threads",
    "post2bluesky": "Publicar no Bluesky",
    "post2mastodon": "Publicar no Mastodon Social",
    "post2linkedin": "Publicar no LinkedIn",
    "post2telegram": "Publicar no Telegram",
    "post2line": "Publicar no LINE",
    "post2tumblr": "Publicar no Tumblr",
    "post2vk": "Publicar no VK",
    "post2weibo": "Publicar no Weibo",
    "post2chatgpt": "Publicar no ChatGPT",
    "post2claude": "Publicar no Claude",
    "onError": "Para usar esta extensão, ela deve estar ativada antes de carregar a página. Tente novamente após atualizar a página no Safari.",
    "settings": "Configurações",
    "quoteStyleSetting": "Aspas",
    "editActions": "Editar ações...",
    "editDone": "Concluído",
    "tooltip": {
      "toggleBullet": "Clique para alternar",
      "dragItem": "Arraste para reordenar"
    }
  },
  "ro": {
    "copy2clipboard": "Copiază în Clipboard",
    "sharelink": "Partajează...",
    "post2x": "Publică pe X",
    "post2threads": "Publică pe Threads",
    "post2bluesky": "Publică pe Bluesky",
    "post2mastodon": "Publică pe Mastodon Social",
    "post2linkedin": "Publică pe LinkedIn",
    "post2telegram": "Publică pe Telegram",
    "post2line": "Publică pe LINE",
    "post2tumblr": "Publică pe Tumblr",
    "post2vk": "Publică pe VK",
    "post2weibo": "Publică pe Weibo",
    "post2chatgpt": "Publică pe ChatGPT",
    "post2claude": "Publică pe Claude",
    "onError": "Pentru a folosi această extensie, trebuie să fie activată înainte de a încărca pagina. Te rugăm să încerci din nou după ce ai reîncărcat pagina în Safari.",
    "settings": "Setări",
    "quoteStyleSetting": "Ghilimele",
    "editActions": "Editează acțiunile...",
    "editDone": "Finalizat",
    "tooltip": {
      "toggleBullet": "Click pentru a comuta",
      "dragItem": "Trageți pentru a reordona"
    }
  },
  "ru": {
    "copy2clipboard": "Скопировать в буфер обмена",
    "sharelink": "Поделиться...",
    "post2x": "Опубликовать в X",
    "post2threads": "Опубликовать в Threads",
    "post2bluesky": "Опубликовать в Bluesky",
    "post2mastodon": "Опубликовать в Mastodon Social",
    "post2linkedin": "Опубликовать в LinkedIn",
    "post2telegram": "Опубликовать в Telegram",
    "post2line": "Опубликовать в LINE",
    "post2tumblr": "Опубликовать в Tumblr",
    "post2vk": "Опубликовать в VK",
    "post2weibo": "Опубликовать в Weibo",
    "post2chatgpt": "Опубликовать в ChatGPT",
    "post2claude": "Опубликовать в Claude",
    "onError": "Для использования этого расширения его нужно активировать перед загрузкой страницы. Пожалуйста, попробуйте снова после перезагрузки страницы в Safari.",
    "settings": "Настройки",
    "quoteStyleSetting": "Кавычки",
    "editActions": "Редактировать действия...",
    "editDone": "Готово",
    "tooltip": {
      "toggleBullet": "Нажмите для переключения",
      "dragItem": "Перетащите для изменения порядка"
    }
  },
  "sk": {
    "copy2clipboard": "Kopírovať do schránky",
    "sharelink": "Zdieľať...",
    "post2x": "Zverejniť na X",
    "post2threads": "Zverejniť na Threads",
    "post2bluesky": "Zverejniť na Bluesky",
    "post2mastodon": "Zverejniť na Mastodon Social",
    "post2linkedin": "Zverejniť na LinkedIn",
    "post2telegram": "Zverejniť na Telegram",
    "post2line": "Zverejniť na LINE",
    "post2tumblr": "Zverejniť na Tumblr",
    "post2vk": "Zverejniť na VK",
    "post2weibo": "Zverejniť na Weibo",
    "post2chatgpt": "Zverejniť na ChatGPT",
    "post2claude": "Zverejniť na Claude",
    "onError": "Na používanie tohto rozšírenia musí byť aktivované pred načítaním stránky. Skúste to znova po obnovení stránky v Safari.",
    "settings": "Nastavenia",
    "quoteStyleSetting": "Úvodzovky",
    "editActions": "Upraviť akcie...",
    "editDone": "Hotovo",
    "tooltip": {
      "toggleBullet": "Kliknite pre prepnutie",
      "dragItem": "Potiahnite pre zmenu poradia"
    }
  },
  "sv": {
    "copy2clipboard": "Kopiera till urklipp",
    "sharelink": "Dela...",
    "post2x": "Publicera på X",
    "post2threads": "Publicera på Threads",
    "post2bluesky": "Publicera på Bluesky",
    "post2mastodon": "Publicera på Mastodon Social",
    "post2linkedin": "Publicera på LinkedIn",
    "post2telegram": "Publicera på Telegram",
    "post2line": "Publicera på LINE",
    "post2tumblr": "Publicera på Tumblr",
    "post2vk": "Publicera på VK",
    "post2weibo": "Publicera på Weibo",
    "post2chatgpt": "Publicera på ChatGPT",
    "post2claude": "Publicera på Claude",
    "onError": "För att använda denna tillägg måste den vara aktiverad innan sidan laddas. Försök igen efter att du har uppdaterat sidan i Safari.",
    "settings": "Inställningar",
    "quoteStyleSetting": "Citat",
    "editActions": "Redigera åtgärder...",
    "editDone": "Klar",
    "tooltip": {
      "toggleBullet": "Klicka för att växla",
      "dragItem": "Dra för att ändra ordning"
    }
  },
  "th": {
    "copy2clipboard": "คัดลอกไปยังคลิปบอร์ด",
    "sharelink": "แชร์...",
    "post2x": "โพสต์ไปที่ X",
    "post2threads": "โพสต์ไปที่ Threads",
    "post2bluesky": "โพสต์ไปที่ Bluesky",
    "post2mastodon": "โพสต์ไปที่ Mastodon Social",
    "post2linkedin": "โพสต์ไปที่ LinkedIn",
    "post2telegram": "โพสต์ไปที่ Telegram",
    "post2line": "โพสต์ไปที่ LINE",
    "post2tumblr": "โพสต์ไปที่ Tumblr",
    "post2vk": "โพสต์ไปที่ VK",
    "post2weibo": "โพสต์ไปที่ Weibo",
    "post2chatgpt": "โพสต์ไปที่ ChatGPT",
    "post2claude": "โพสต์ไปที่ Claude",
    "onError": "ในการใช้ส่วนขยายนี้ จำเป็นต้องเปิดใช้งานก่อนโหลดหน้าเว็บ กรุณากดปุ่มด้านล่างเพื่อทดลองอีกครั้งหลังจากที่อัปเดตหน้าใน Safari",
    "settings": "การตั้งค่า",
    "quoteStyleSetting": "คำพูด",
    "editActions": "แก้ไขการกระทำ...",
    "editDone": "เสร็จสิ้น",
    "tooltip": {
      "toggleBullet": "คลิกเพื่อสลับ",
      "dragItem": "ลากเพื่อจัดลำดับใหม่"
    }
  },
  "tr": {
    "copy2clipboard": "Panoya Kopyala",
    "sharelink": "Paylaş...",
    "post2x": "X'e Gönder",
    "post2threads": "Threads'e Gönder",
    "post2bluesky": "Bluesky'e Gönder",
    "post2mastodon": "Mastodon Social'e Gönder",
    "post2linkedin": "LinkedIn'e Gönder",
    "post2telegram": "Telegram'a Gönder",
    "post2line": "LINE'a Gönder",
    "post2tumblr": "Tumblr'a Gönder",
    "post2vk": "VK'a Gönder",
    "post2weibo": "Weibo'a Gönder",
    "post2chatgpt": "ChatGPT'ye Gönder",
    "post2claude": "Claude'a Gönder",
    "onError": "Bu uzantıyı kullanmak için, sayfayı yüklemeden önce etkinleştirilmiş olmalıdır. Safari'de sayfayı yeniledikten sonra tekrar deneyin.",
    "settings": "Ayarlar",
    "quoteStyleSetting": "Tırnak İşaretleri",
    "editActions": "Eylemleri Düzenle...",
    "editDone": "Tamam",
    "tooltip": {
      "toggleBullet": "Açıp kapatmak için tıklayın",
      "dragItem": "Yeniden sıralamak için sürükleyin"
    }
  },
  "uk": {
    "copy2clipboard": "Скопіювати в буфер обміну",
    "sharelink": "Поділитися...",
    "post2x": "Опублікувати в X",
    "post2threads": "Опублікувати в Threads",
    "post2bluesky": "Опублікувати в Bluesky",
    "post2mastodon": "Опублікувати в Mastodon Social",
    "post2linkedin": "Опублікувати в LinkedIn",
    "post2telegram": "Опублікувати в Telegram",
    "post2line": "Опублікувати в LINE",
    "post2tumblr": "Опублікувати в Tumblr",
    "post2vk": "Опублікувати в VK",
    "post2weibo": "Опублікувати в Weibo",
    "post2chatgpt": "Опублікувати в ChatGPT",
    "post2claude": "Опублікувати в Claude",
    "onError": "Щоб використовувати це розширення, воно повинно бути увімкнене перед завантаженням сторінки. Спробуйте знову після оновлення сторінки в Safari.",
    "settings": "Налаштування",
    "quoteStyleSetting": "Лапки",
    "editActions": "Редагувати дії...",
    "editDone": "Готово",
    "tooltip": {
      "toggleBullet": "Натисніть, щоб перемкнути",
      "dragItem": "Перетягніть для зміни порядку"
    }
  },
  "vi": {
    "copy2clipboard": "Sao chép vào Clipboard",
    "sharelink": "Chia sẻ...",
    "post2x": "Đăng lên X",
    "post2threads": "Đăng lên Threads",
    "post2bluesky": "Đăng lên Bluesky",
    "post2mastodon": "Đăng lên Mastodon Social",
    "post2linkedin": "Đăng lên LinkedIn",
    "post2telegram": "Đăng lên Telegram",
    "post2line": "Đăng lên LINE",
    "post2tumblr": "Đăng lên Tumblr",
    "post2vk": "Đăng lên VK",
    "post2weibo": "Đăng lên Weibo",
    "post2chatgpt": "Đăng lên ChatGPT",
    "post2claude": "Đăng lên Claude",
    "onError": "Để sử dụng tiện ích mở rộng này, bạn phải kích hoạt nó trước khi tải trang. Vui lòng thử lại sau khi làm mới trang trong Safari.",
    "settings": "Cài đặt",
    "quoteStyleSetting": "Dấu ngoặc kép",
    "editActions": "Chỉnh sửa hành động...",
    "editDone": "Xong",
    "tooltip": {
      "toggleBullet": "Nhấp để chuyển đổi",
      "dragItem": "Kéo để sắp xếp lại"
    }
  },
  "zh": {
    "copy2clipboard": "复制到剪贴板",
    "sharelink": "共享...",
    "post2x": "发布到 X",
    "post2threads": "发布到 Threads",
    "post2bluesky": "发布到 BlueSky",
    "post2mastodon": "发布到 Mastodon Social",
    "post2linkedin": "发布到 LinkedIn",
    "post2telegram": "发布到 Telegram",
    "post2line": "发布到 LINE",
    "post2tumblr": "发布到 Tumblr",
    "post2vk": "发布到 VK",
    "post2weibo": "发布到 Weibo",
    "post2chatgpt": "发布到 ChatGPT",
    "post2claude": "发布到 Claude",
    "onError": "要使用此扩展程序，必须在加载页面之前启用。请在 Safari 中刷新页面后重试。",
    "settings": "设置",
    "quoteStyleSetting": "引号",
    "editActions": "编辑操作...",
    "editDone": "完成",
    "tooltip": {
      "toggleBullet": "点击切换",
      "dragItem": "拖动重新排序"
    }
  },
  "zh-CN": {
    "copy2clipboard": "复制到剪贴板",
    "sharelink": "共享...",
    "post2x": "发布到 X",
    "post2threads": "发布到 Threads",
    "post2bluesky": "发布到 BlueSky",
    "post2mastodon": "发布到 Mastodon Social",
    "post2linkedin": "发布到 LinkedIn",
    "post2telegram": "发布到 Telegram",
    "post2line": "发布到 LINE",
    "post2tumblr": "发布到 Tumblr",
    "post2vk": "发布到 VK",
    "post2weibo": "发布到 Weibo",
    "post2chatgpt": "发布到 ChatGPT",
    "post2claude": "发布到 Claude",
    "onError": "要使用此扩展程序，必须在加载页面之前启用。请在 Safari 中刷新页面后重试。",
    "settings": "设置",
    "quoteStyleSetting": "引号",
    "editActions": "编辑操作...",
    "editDone": "完成",
    "tooltip": {
      "toggleBullet": "点击切换",
      "dragItem": "拖动重新排序"
    }
  },
  "zh-TW": {
    "copy2clipboard": "複製到剪貼簿",
    "sharelink": "分享...",
    "post2x": "發佈到 X",
    "post2threads": "發佈到 Threads",
    "post2bluesky": "發佈到 BlueSky",
    "post2mastodon": "發佈到 Mastodon Social",
    "post2linkedin": "發佈到 LinkedIn",
    "post2telegram": "發佈到 Telegram",
    "post2line": "發佈到 LINE",
    "post2tumblr": "發佈到 Tumblr",
    "post2vk": "發佈到 VK",
    "post2weibo": "發佈到 Weibo",
    "post2chatgpt": "發佈到 ChatGPT",
    "post2claude": "發佈到 Claude",
    "onError": "要使用此擴充功能，必須在載入頁面之前啟用。請在 Safari 中重新載入頁面後再試一次。",
    "settings": "設定",
    "quoteStyleSetting": "引號",
    "editActions": "編輯操作...",
    "editDone": "完成",
    "tooltip": {
      "toggleBullet": "點擊切換",
      "dragItem": "拖動重新排序"
    }
  },
  "zh-HK": {
    "copy2clipboard": "複製到剪貼簿",
    "sharelink": "分享...",
    "post2x": "發佈到 X",
    "post2threads": "發佈到 Threads",
    "post2bluesky": "發佈到 BlueSky",
    "post2mastodon": "發佈到 Mastodon Social",
    "post2linkedin": "發佈到 LinkedIn",
    "post2telegram": "發佈到 Telegram",
    "post2line": "發佈到 LINE",
    "post2tumblr": "發佈到 Tumblr",
    "post2vk": "發佈到 VK",
    "post2weibo": "發佈到 Weibo",
    "post2chatgpt": "發佈到 ChatGPT",
    "post2claude": "發佈到 Claude",
    "onError": "要使用此擴充功能，必須在載入頁面之前啟用。請在 Safari 中重新載入頁面後再試一次。",
    "settings": "設定",
    "quoteStyleSetting": "引號",
    "editActions": "編輯操作...",
    "editDone": "完成",
    "tooltip": {
      "toggleBullet": "點擊切換",
      "dragItem": "拖動重新排序"
    }
  },
};

export const getCurrentLangLabelString = (key = 'onError') => {
  const langCode = window.navigator.language || 'en';
  const baseLang = langCode.split('-')[0];

  return (
    labelStrings[langCode]?.[key] ??
    labelStrings[baseLang]?.[key] ??
    labelStrings.en[key]
  );
};

export const applyRTLSupport = () => {
  const langCode = window.navigator.language || 'en';
  const baseLang = langCode.split('-')[0];

  if (baseLang === 'ar' || baseLang === 'he') {
    document.body.classList.add('rtl');
    document.documentElement.setAttribute('lang', baseLang);
    document.documentElement.setAttribute('dir', 'rtl');
  } else {
    document.body.classList.remove('rtl');
    document.documentElement.removeAttribute('dir');
  }
};
